package com.appdirect;

public enum ErrorCode {

	USER_NOT_FOUND,
	ACCOUNT_NOT_FOUND,
	MAX_USERS_REACHED,
	UNAUTHORIZED,
	OPERATION_CANCELED,
	CONFIGURATION_ERROR,
	INVALID_RESPONSE,
	PENDING,
	FORBIDDEN,
	BINDING_NOT_FOUND,
	TRANSPORT_ERROR,
	UNKNOWN_ERROR;
}
